#!/bin/sh

# Copyright 2015-2016 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

export GHCRTS="$GHCRTS -M1G"
#GHCFLAGS="$GHCFLAGS -Wall"

MODDIR=src
HS=$(echo $(basename $0) | sed -e 's/\(\.[^.\/]*\)\?$/.hs/')

runghc $GHCFLAGS -i$MODDIR "$MODDIR/$HS" "$@"

